### ISSUE TITLE
Nothing happens after connecting the Bluepill's USB to the computer

### ISSUE THREAD

**Issue by classbproject** [usbcnc/grbl#47]
Hi, I was able to successfully build and upload the HEX file to the Bluepill. However, after I plugged in the USB cable to the computer, nothing happened. There was no new COM port that I could see. Am I missing something?

**Comment by robomechs** [comment]
Have you already installed the driver?
http://www.st.com/en/development-tools/stsw-stm32102.html

**Comment by classbproject** [comment]
Yes I did. I even tried different cables. Nothing. Windows doesn’t even say that new hardware was detected. I looked through the traces on the board and there seem to be 22R resistors in series with the D+ and D- lines.

**Comment by robomechs** [comment]
R9, R11 (22R) is ok. Some people have problem with R10 (10k), it have to be 1,5k according to the standard.
Because of this in some cases, the board is not connected via usb. This has already been discussed here, if I'm not mistaken. It's a known bug of this board. Тry a few other computers. If on any of them the board connects, then most likely the problem is in the 10k pull-up resistor.
![arduino_stm32f103c8t6_schematics](https://user-images.githubusercontent.com/8062959/41457227-a6ce2d5e-708b-11e8-8085-2bd0c9bca5b4.png)

**Comment by SailWithChips** [comment]
Hi, I had similar problems... I have experimented that If I supply voltage before and some ms after that I plug the USB then, everything worked fine for me. Can you try?

**Comment by classbproject** [comment]
@yaroslavVl Thank you. I was not aware of that. I didn't have a 1.5K on hand but did have a 1.2K and that seemed to have solved the problem. I can now see the USB enumerating as a COM port.
